### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by xtc4779** [fr0st-iwnl/kiyokomacro#9] opened 2024-11-23 14:26 UTC
![Screenshot 2024-11-23 092312](https://github.com/user-attachments/assets/d41f18e6-47ce-4804-8063-e53c701229a4)
![Screenshot 2024-11-23 092421](https://github.com/user-attachments/assets/184bba1d-4092-48ec-8f4d-9f4eb3e290a5)
![Screenshot 2024-11-23 092432](https://github.com/user-attachments/assets/d2ed423c-a4f8-4959-b221-c499e309f0c5)
 The missing i con still persists, for some reason the main mighty omega macro is the only one that works for me , for some reason it just wont let me bypass this . I used winrar to extract and it still persists. In the first image is how my files extracted, in the second is how the icons are viewed and the second is me opening said icon files and noticing they look completely fine.PLEASE help im desperately trying to use your macro but it jsut wont work for me.

**Comment by fr0st-iwnl** [comment] 2024-11-23 20:19
It seems this issue was resolved, but in the past, you had to extract the file twice for it to work. Now, if it still doesn’t work, it’s likely a **you** issue. I suggest trying to `git clone` the repo directly and see if that fixes it

**Comment by xtc4779** [comment] 2024-11-23 22:25
how exactly can i do this im not to experienced

**Comment by fr0st-iwnl** [comment] 2024-11-23 22:46
Install [GIT](https://git-scm.com/downloads) and once it's installed, open your terminal (`Git Bash`) and run the following commands:

```bash
cd Downloads
```

```bash
git clone https://github.com/fr0st-iwnl/kiyokomacro.git
```

**Comment by xtc4779** [comment] 2024-11-23 23:51
![image](https://github.com/user-attachments/assets/20026a88-d6f0-4833-9d44-194e0882592a)
i was able to create the copy but still no luck could it have anything thing to do with my ahk file appearing blank 
![image](https://github.com/user-attachments/assets/bb50bf08-f20a-403f-b727-e38cc3830e3c)

**Comment by xtc4779** [comment] 2024-11-23 23:52
on my rdp desktop it appears with a ahk icon

**Comment by fr0st-iwnl** [comment] 2024-11-24 00:03
> ![image](https://private-user-images.githubusercontent.com/189458794/389236383-20026a88-d6f0-4833-9d44-194e0882592a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MDYyMTIsIm5iZiI6MTczMjQwNTkxMiwicGF0aCI6Ii8xODk0NTg3OTQvMzg5MjM2MzgzLTIwMDI2YTg4LWQ2ZjAtNDgzMy05ZDQ0LTE5NGUwODgyNTkyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QyMzUxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzBiNjI3ZDUwYjJkMjFjNWQ1ZTM1N2I5NmZiNDk0NzU5NTRmMzRhMWFjMTQ4NTU4OWYzYzExMGMxZGI2YTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fq1_0GqsE9TQ9EP7pT-5asB0ryKJpRoPKI1VWORyyNo) i was able to create the copy but still no luck could it have anything thing to do with my ahk file appearing blank ![image](https://private-user-images.githubusercontent.com/189458794/389236518-bb50bf08-f20a-403f-b727-e38cc3830e3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MDYyMTIsIm5iZiI6MTczMjQwNTkxMiwicGF0aCI6Ii8xODk0NTg3OTQvMzg5MjM2NTE4LWJiNTBiZjA4LWYyMGEtNDAzZi1iNzI3LWUzOGNjMzgzMGUzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QyMzUxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmJiY2RjMGZkYTRlMThkODIzMzA4NTA1NjM0N2M1MGQyYWY2NjUzY2IwMWQ3ZGQxMjkxYTMyMDg0ZDVkMDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TLu_Wa4jLjhOp9nEungiBg2vIaRI0UDLHOEUc7BolWg)



open it with ahk

**Comment by xtc4779** [comment] 2024-11-24 00:05
i do but still nothing
![image](https://github.com/user-attachments/assets/d775029a-8bd4-41db-9387-b0bc919f9d63)

**Comment by fr0st-iwnl** [comment] 2024-11-24 00:15
> i do but still nothing ![image](https://private-user-images.githubusercontent.com/189458794/389237826-d775029a-8bd4-41db-9387-b0bc919f9d63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MDcwNTEsIm5iZiI6MTczMjQwNjc1MSwicGF0aCI6Ii8xODk0NTg3OTQvMzg5MjM3ODI2LWQ3NzUwMjlhLThiZDQtNDFkYi05Mzg3LWIwYmM5MTlmOWQ2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwMDA1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWM3YWRiYjEzYjIxZTM3MDQ4ZWVhMTk2OTU2OGZiYjk2ZTcwZjU3MDA5NWE4ZTE1Njc1OGMwOTJiMDQwZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vrqLyUg8ZZwwjatb115gZOxpqv2a4SCwrFh4OcWSqT4)

hm weird can u try to get this one from this [branch](https://github.com/fr0st-iwnl/kiyokomacro/tree/dev) i just updated it maybe it works

**Comment by xtc4779** [comment] 2024-11-24 00:28
![image](https://github.com/user-attachments/assets/a334e84a-b09e-4a93-bd34-9c90a096d9c1)
😭

**Comment by fr0st-iwnl** [comment] 2024-11-24 00:52
try to get it again i changed something and maybe now it works

**Comment by xtc4779** [comment] 2024-11-24 01:06
![image](https://github.com/user-attachments/assets/4a86f5dc-7ae7-410f-b4de-769164caceaf)
 
i just extracted and installed regularly should i git repo it?

**Comment by fr0st-iwnl** [comment] 2024-11-24 01:28
I've added debugging logs try reinstalling the macro or cloning it again using Git. If the issue persists again its a ***you*** issue/problem, as i'm unable to reproduce it...

**Comment by fr0st-iwnl** [comment] 2024-11-24 01:35
btw a debug.log file should show up lmk what it says. If it doesn’t then like i said its a you problem and it means that you didn’t extract the files properly.

**Comment by xtc4779** [comment] 2024-11-24 01:41
no matter what i do it continues to give me icon missing

**Comment by fr0st-iwnl** [comment] 2024-11-24 01:53
> no matter what i do it continues to give me icon missing

If it still says the icon is missing, it just means you didn’t extract the files. I can’t reproduce the issue, so I’ll close this now.

**Closed by fr0st-iwnl** 2024-11-24 01:53 UTC
