### ISSUE TITLE
Treadmill and Striking Power

### ISSUE THREAD

**Issue by blackwatermelonzz** [fr0st-iwnl/kiyokomacro#24] opened 2024-12-24 01:08 UTC
### Already reported? *

- [X] I have searched the existing open and closed issues.

### Did you check the FAQ? *

- [X] I have read the FAQ.

### Description

The Treadmill macro wont start at all and the striking power macro it just starts hitting the bag instead of making me sweat first 

### How to reproduce

How can I fix this

**Comment by fr0st-iwnl** [comment] 2024-12-24 08:13
Duplicate of this issue #8 . it's probably because you have the new **UI**. Refer to this issue for details.

**Comment by blackwatermelonzz** [comment] 2024-12-25 03:39
Bloxstrap does have the option to change the UI anymore it got removed

**Comment by fr0st-iwnl** [comment] 2024-12-25 09:51
You can still change the UI in Bloxstrap just use the `BloxstrapUI.bat` file that i created just read what i said in this picture [ [FAQ] ](https://kiyokosmacros.netlify.app/faq)
---
![image](https://github.com/user-attachments/assets/33545003-d4f9-46a6-a286-68ad36759203)

**Closed by fr0st-iwnl** 2024-12-25 09:51 UTC
Labels: bug

**Comment by blackwatermelonzz** [comment] 2024-12-25 22:04
okay yeah I didnt see the run anyway (i had to click more info) when i clicked on the bloxstrap.bat tool... tysm
