### ISSUE TITLE
Striking Power Macro

### ISSUE THREAD

**Issue by Icyy711** [fr0st-iwnl/kiyokomacro#7] opened 2024-11-15 17:07 UTC
I have looked at the FAQ to try to figure out this issue i have also seen many people looking for a answer to this issue. So it started off with the macro not running at all and punching off the bat, but now after putting the command in bloxstrap it runs for like maybe 5 seconds then stops and then repeats. Now its very possible I'm just doing something wrong but I cant figure it out. 

Also linking a video

https://github.com/user-attachments/assets/c41b4452-5c3f-49ab-9960-77b0a1ccd04d

Lmk if i can provide any additional information, or if that clip doesnt work.

**Comment by fr0st-iwnl** [comment] 2024-11-15 18:01
Have you tried other servers?

**Comment by Icyy711** [comment] 2024-11-15 18:03
like a different MO server? I have yea

**Comment by fr0st-iwnl** [comment] 2024-11-15 18:05
whats ur ping?

**Comment by Icyy711** [comment] 2024-11-15 18:06
like a 60-70 avg sometimes spikes to 80

**Comment by fr0st-iwnl** [comment] 2024-11-15 18:07
hmm, that's weird. i haven't seen that issue before. maybe it's a keyboard language problem. have you checked the language settings?

**Comment by Icyy711** [comment] 2024-11-15 18:08
English (US)

**Comment by fr0st-iwnl** [comment] 2024-11-15 18:12
yeah, i'm not sure either. maybe try other servers for now. i'll look into it after I switch back to Windows but since i'm sick and can't do anything about it right now, it might take a few days or weeks. if you manage to fix it, let me know.

**Comment by Icyy711** [comment] 2024-11-15 18:16
yea no worries its not an urgent thing for me, I will keep you updated if I figure anything out.

**Comment by Icyy711** [comment] 2024-11-16 02:59
just to update you rq strike speed works and most of the other macros I tested so now I'm even more confused as to why sp is the only one that wont.

**Comment by Icyy711** [comment] 2024-11-19 13:11
not sure why but for some reason it worked in a random Dallas server that was 5 days old, I'm not sure what the reason would be.
only thing I can think of is every server I joined was a bad server, but I would think that to be highly unlikely. Gonna check later if it just works now or if its just the server im in. Will let you know

**Comment by fr0st-iwnl** [comment] 2024-11-19 15:31
> not sure why but for some reason it worked in a random Dallas server that was 5 days old, I'm not sure what the reason would be. only thing I can think of is every server I joined was a bad server, but I would think that to be highly unlikely. Gonna check later if it just works now or if its just the server im in. Will let you know

alright!

**Comment by fr0st-iwnl** [comment] 2024-11-20 16:04
> It seems to be just working now haven't had a issue, still confused though only thing I've done is get more stats in game and then i downloaded yolos macro for sp and ever since that its worked.

It might be due to the servers. The issue is really weird because I've never seen it happen to anyone else. btw can i close this issue?

**Closed** 2024-11-21 00:06 UTC
